# Generated by Django 6.1 on 2026-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional. Set this to show a strikethrough 'was' price.", max_digits=8, null=True),
        ),
    ]
